name: Step 2 - Build VSIX packages

on:
  workflow_run:
      workflows: ["Step 1 - Update Fork and Apply Patches"]
      types:
        - completed
  workflow_dispatch:
    inputs:
      tags:
        description: 'Run this manually'
        required: false
        type: boolean

jobs:
  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup dotnet
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.x'

    - name: Install Node.js 18.x
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
        registry-url: https://registry.npmjs.org/

    - name: Install dependencies
      run: |
          npm add tar
          npm add --save-dev @types/tar
          npm ci
          npm i -g gulp
    - name: Lint fix
      run: npx eslint ./ --fix
    - name: Compile
      run: npm run compile

    - name: Prepublish VSIXs
      run: npm run vscode:prepublish

    - name: Build VSIXs
      run: gulp 'vsix:release:package'

    - name: Display structure of built packages
      run: |
        ls -R ./vsix

    - name: Upload build artifact (darwin-x64)
      id: upload-release-asset-darwin-x64
      uses: actions/upload-artifact@v4
      with:
        path: ./vsix/csharp-darwin-x64-*.vsix
        name: csharp-darwin-x64.vsix

    - name: Upload build artifact (linux-x64)
      id: upload-release-asset-linux-x64
      uses: actions/upload-artifact@v4
      with:
        path: ./vsix/csharp-linux-x64-*.vsix
        name: csharp-linux-x64.vsix

    - name: Upload build artifact (win32-x64)
      id: upload-release-asset-win32-x64
      uses: actions/upload-artifact@v4
      with:
        path: ./vsix/csharp-win32-x64-*.vsix
        name: csharp-win32-x64.vsix

    - name: Upload build artifact (platform-neutral)
      uses: actions/upload-artifact@v4
      with:
        path: ./vsix/csharp-[0-9.]*.vsix
        name: csharp-platform-neutral.vsix