parameters:
  - name: pool
    type: object
  - name: containerName
    type: string
    default: ''
  - name: dotnetVersion
    type: string
  - name: installAdditionalLinuxDependencies
    type: boolean
    default: false
  - name: testVSCodeVersion
    type: string

jobs:
- job:
  strategy:
    matrix:
      CSharpTests:
        npmCommand: 'test:unit' # Restore when integration test are stable: 'test:withoutDevKit'
      DevKitTests:
        npmCommand: test:integration:devkit
  pool: ${{ parameters.pool }}
  ${{ if parameters.containerName }}:
    container: ${{ parameters.containerName }}
  steps:
  - template: /azure-pipelines/test.yml@self
    parameters:
      dotnetVersion: ${{ parameters.dotnetVersion }}
      installAdditionalLinuxDependencies: true
      npmCommand: $(npmCommand)
      testVSCodeVersion: ${{ parameters.testVSCodeVersion }}