parameters:
  - name: pool
    type: object
  - name: containerName
    type: string
    default: ''
  - name: dotnetVersion
    type: string
  - name: installAdditionalLinuxDependencies
    type: boolean
    default: false
  - name: testVSCodeVersion
    type: string

jobs:
- job:
  strategy:
    matrix:
      UnitTests:
        npmCommand: test:unit
      CSharpIntegrationTests:
        npmCommand: test:integration:csharp
      DevKitTests:
        npmCommand: test:integration:devkit
      RazorTests:
        npmCommand: test:integration:razor
  pool: ${{ parameters.pool }}
  ${{ if parameters.containerName }}:
    container: ${{ parameters.containerName }}
  steps:
  - template: /azure-pipelines/test.yml@self
    parameters:
      dotnetVersion: ${{ parameters.dotnetVersion }}
      installAdditionalLinuxDependencies: true
      npmCommand: $(npmCommand)
      testVSCodeVersion: ${{ parameters.testVSCodeVersion }}